### ISSUE TITLE
Multiline codec needs a max_age option

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-codec-multiline#11]
From @mvintila : https://github.com/elastic/logstash/issues/3936

---

Currently, by using the multiline codec on input, you never get the last message from the logs.

The codec will wait forever for the next line to come in order to check it against the pattern. This is OK if the source is very active, but for sources that produce 1 message every hour or so the multiline codec is simply not usable.

The multiline filter covers the above scenario but it has it's own problems ( not thread safe and #3935 ).

**Comment by ph** [comment]
This problem somewhat related to this https://github.com/logstash-plugins/logstash-input-beats/issues/23

**Comment by guyboertje** [comment]
This is a known issue (to me anyway) that is capable of being solved with the IdentityMapCodec wrapping the multiline codec.

So far we have done this on the file input and the beats input.

In the case of the file input, the codec buffer containing the last lines captured, will be flushed after one hour of inactivity.  One hour is the default but it can be changed from the input code.

@mvintila - If you are using the file input with the multiline codec then you should try v2.0.3 of the file input.

**Comment by guyboertje** [comment]
This feature cannot be implemented, as asked for, without a significant refactor of the pipeline <-> input <-> codec APIs.  This is because the design does not allow for async out-of-band event propagation downstream.  There is no code path codec -> input -> pipeline.

**Comment by guyboertje** [comment]
@ph and I have found a way to realise auto-flush without a significant refactor of the pipeline <-> input interactions. This way will be a stepping stone to the refactor. This affects all inputs that might need multiline and the multiline codec and the filewatch library.  There is a PR for the first step [here](https://github.com/jordansissel/ruby-filewatch/pull/71) with more PR to follow.
