### ISSUE TITLE
Document interval unit for auto flush interval

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-codec-multiline#20]
We added auto_flush_interval but did not specify what time unit the configuration parameter expects.

https://github.com/logstash-plugins/logstash-codec-multiline/blob/47640894c72f028b172a6b35b9783b5e80ce38ab/lib/logstash/codecs/multiline.rb#L130

Based on the executor method (http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/ScheduledTask.html#execute-class_method) we are calling from AutoFlush class, pretty sure that it expects the time unit to be in seconds.  Let's document this accordingly :)

**Comment by guyboertje** [comment]
Yes, it is seconds. Will document.
