### ISSUE TITLE
Memory Leak issue

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-codec-multiline#28]
I am using a simple configuration:

```
input {

    file {

        type => "one_type"

        start_position => "end"

        path => [

        "/Users/Gabriel/Documents/ElasticSearch/Test/logstash-2.1.2/logs/*"

        ]

        sincedb_path => "/Users/Gabriel/Documents/ElasticSearch/Test/.sincedb"

        codec => multiline {

        auto_flush_interval => 120

        max_lines => 100

        max_bytes => "10 MiB"

        pattern => "NVRAZBYCX"

        what => "next"

        negate => true

        }

    }

}

filter {

    drop{}

}
```

And generating random lines of logs using a simple command line that writes new lines to a log inside `logs` folder.

The memory consumption is going up and up with no stop, and looks like the GC is not being able to collect much garbage:

<img width="422" alt="screen shot 2016-02-08 at 15 07 46" src="https://cloud.githubusercontent.com/assets/1675411/12894939/a8a0f344-ce78-11e5-80f5-7dcabd2a3027.png">

I generated a heap dump from the logstash instance and got the following:

HTML to be opened on a browser (remove the .txt since Github prevents people from uploading html):

[Objects-by-class.html.txt](https://github.com/logstash-plugins/logstash-codec-multiline/files/122006/Objects-by-class.html.txt)

Image:

<img width="1428" alt="screen shot 2016-02-08 at 15 30 44" src="https://cloud.githubusercontent.com/assets/1675411/12894983/f6dfee7a-ce78-11e5-81ef-088be4000b07.png">

**Comment by gmoskovicz** [comment]
Same test without the `auto_flush_interval` is showing better results:

<img width="393" alt="screen shot 2016-02-08 at 15 49 42 1" src="https://cloud.githubusercontent.com/assets/1675411/12895504/977299e4-ce7b-11e5-8880-783d51019e6d.png">

**Comment by guyboertje** [comment]
I can confirm that a library we use `concurrent_ruby` is not fully removing cancelled timer tasks.

I am working on two solutions for two different scenarios.
- when ML is used without identity mapping, e.g. stdin input. I have a solution for this that uses one timer.
- when ML is used with identity mapping, .e.g. file input. Here we can't have a timer per codec as each file path (identity) seen creates a copy of the codec and therefore a timer and a timer thread - 20K files = 20K codecs = 20K timer threads.  I have a solution and am coding it now.

**Comment by ph** [comment]
I can confirm that #29 PR fixes this issue, I used @gmoskovicz configuration and a script that generate log line. I ran the scripts for 2 hours and monitored the memory usager. GC was correctly behaving with no leak.

**Comment by gmoskovicz** [comment]
Thanks for taking care of this @ph @guyboertje
