### ISSUE TITLE
unbounded buffer can cause OutOfMemoryError 

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-codec-multiline#4]
there is no check on the number of lines buffered or on the total buffer size so the codec can end up in endlessly buffering until reaching and out of memory exception. 

also mentioned in https://logstash.jira.com/browse/LOGSTASH-2133

**Comment by colinsurprenant** [comment]
rewrote @suyograo description & first comment.

**Comment by allenmchan** [comment]
Will the fix for this get into 1.5?

**Comment by suyograo** [comment]
@allenmchan we are evaluating fixes for this. we will update here once we know more.

**Comment by ph** [comment]
fix in the latest version of the plugin. 0.1.7

**Comment by dkoshkin** [comment]
Is there an option to increase the number of lines per message allowed, or a way to combine messages if they are multiline_codec_max_lines_reached? I work with long SOAP responses and sometimes the respones are longer than can be displayed. Thanks

**Comment by ph** [comment]
You can use `max_lines` it default to 500, there also a `max_bytes` options, first one reached will break the message.

**Comment by abordia** [comment]
![captureleaksuspect1](https://cloud.githubusercontent.com/assets/11634420/8868463/98086874-318d-11e5-89e0-d6ea64929c16.JPG)

Hi,
I am getting OOM on logstash process.  Attached is MAT snapshot.  How can i conclude if this is related to multiline filter?  I am using various filters like multiline, kv, grok, mutate.  Any other insight in fixing this leak will be helpful.  Thank you
