### ISSUE TITLE
Multilines over boundry bypass input processing, codecs

### ISSUE THREAD

**Issue by technosf** [logstash-plugins/logstash-codec-multiline#9]
Logstash 1.5, ES 1.6, Windows

I have Multiline as a codec joining logs that may have XML. Some of the log entries grow to over 500 lines because of line breaks in the XML.

I am finding that Mulitline codec splits these lines so that the 501st line and on are treated as a new Multiline match - even though the 501st line does not match the Multiline pattern and should continue to be part of the preceding multiline.

I.e. there are two issues:

  o  Entries that span > 500 line breaks are truncated at 500 lines
  o  Entries that span > 500 line breaks trigger a false match from line 501 on

**Comment by ph** [comment]
Hello,  you can set the 'max_lines' option of the plugin to something higher,  the default is 500. We uses that limit and the 'max_bytes' options as circuit breaker to make sure logstash don't go oom , the first option reached will flush the event. You can play with the limits to make sure you don't miss events.

**Comment by technosf** [comment]
Ah... Thank you.

Must have been looking at the Multiline filter doc.

**Comment by technosf** [comment]
Ah... 

Sorry to close and reopen - I think the behavior at the max_lines is buggy. Spliting the mulitiline at, say 500, then the new line should go through the pipeline anew from the input section.

Currently, its split and appears to be processed from the filters section on, ignoring input codecs etc.

**Comment by ph** [comment]
I am not sure I understand what you mean here, the current behavior is force a flush if one of the two conditions match and tag the event with "multiline_codec_max_bytes_reached" or  "multiline_codec_max_lines_reached" and it will run until we can create a new "multiline" event.

Can you give me more details on this part?

> its split and appears to be processed from the filters section on, ignoring input codecs etc.

**Comment by ph** [comment]
No problem in reopening your issue lets make sure we go through the problem and fix it :)

**Comment by technosf** [comment]
At this point, it's not an issue per se, but I have two observations.

1) Having a filter and a codec with the same name - Google may take you to the wrong place, causing confusion.

2) The codec works as defined in the doc, but I think the doc can better expound how it works.
Specifically, the behavior once max_lines has been reach, or if the line break patter has been found, should be called out. I.e. that the codec processes all lines, coalescing them all, and that everything is flushed into the pipeline. I would also add the max_lines param to the example in order to call out the flush behavior.

Thinking through the efficacy of the codec and the filter, I think it would be reasonable to add filter functionality to the codec - that once the buffer is full, or before the break pattern is matched, that the buffer is truncated causing no further processing to occur on that input.

Thoughts?
